configurations/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls'))   # added url of Polls app
]

polls/urls.py
from django.urls import path

from polls import views

app_name = 'polls'
urlpatterns = [
    path('index/', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('', views.FirstView.as_view(), name='first'),
]

polls/models.py
from django.db import models

# Create your models here.


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.views.generic import TemplateView

from .models import Choice, Question


class IndexView(generic.ListView):
    # Give template to redirect and context.
    template_name = 'index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    # Provided Model and template name
    model = Question
    template_name = 'detail.html'


class ResultsView(generic.DetailView):
    # Provided Model and template name
    model = Question
    template_name = 'results.html'


def vote(request, question_id):
    # print(request.POST['choice'])
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


class FirstView(TemplateView):
    # Provided template name
    template_name = "first.html"

polls/templates/detail.html
{% extends 'base.html' %}	<!--Extension of base.html File-->
{% block content %}
<a class ="btn btn-secondary btn-sm mb-3" href ="{% url 'polls:index' %}">Back To Polls</a>
<h1 class ="text-center mb-3">{{ question.question_text }}</h1>

<!--If there is an error message then display it.-->
{% if error_message %}
<p class ="alert alert-danger">
	<strong>{{ error_message }}</strong>
</p>

{% endif %}

<!--Display Question and list of choices to vote-->
<form action ="{% url 'polls:vote' question.id %}" method ="post">
	{% csrf_token %}

	<!--Display of Choice-->
	{% for choice in question.choice_set.all %}
	<div class ="form-check">
		<input type ="radio" name ="choice" class ="form-check-input" id ="choice{{ forloop.counter }}"
			value ="{{ choice.id }}" />
		<label for ="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
	</div>
	{% endfor %}
	<input type ="submit" value ="Vote" class ="btn btn-success btn-lg btn-block mt-4" />
</form>
{% endblock %}

polls/templates/first.html
{% extends 'base.html' %}	<!--Extension of base.html File-->
{% block content %}

<div class ="card text-center">
	<div class ="card-body">
		<h1>Welcome To Polling App</h1>
		
		<a class ="btn btn-dark" href ="{% url 'polls:index' %}">
			View Available Polls</a>
	</div>
</div>
{% endblock %}

polls/templates/index.html
{% extends 'base.html' %}
{% block content %}
<h1 class ="text-center mb-3">Poll Questions</h1>

<!--If there are questions in list then display it-->
{% if latest_question_list %}
{% for question in latest_question_list %}
<div class ="card-mb-3">
	<div class ="card-body">
		<p class ="lead">{{ question.question_text }}</p>

		<a href ="{% url 'polls:detail' question.id %}" class ="btn btn-primary btn-sm">Vote Now</a>
		<a href ="{% url 'polls:results' question.id %}" class ="btn btn-secondary btn-sm">Results</a>
	</div>
</div>
{% endfor %}
{% else %}

<p>No polls available</p>

{% endif %}
{% endblock %}

polls/templates/results.html
{% extends 'base.html' %}
{% block content %}
<h1 class ="mb-5 text-center">{{ question.question_text }}</h1>

<!--Display the Votes of Question-->
<ul class ="list-group mb-5">
    {% for choice in question.choice_set.all %}
    <li class ="list-group-item">
        {{ choice.choice_text }} <span class ="badge badge-success float-right">{{ choice.votes }}
            vote{{ choice.votes | pluralize }}</span>
    </li>
    {% endfor %}
</ul>
 
<a class ="btn btn-secondary" href ="{% url 'polls:index' %}">Back To Polls</a>
<a class ="btn btn-dark" href ="{% url 'polls:detail' question.id %}">Vote again?</a>
{% endblock %}

templates/base.html
<html lang ="en">
<head>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" 
	integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<title>Polls App {% block title %}{% endblock %}</title>
</head>

<body>
	<!--Navigation Bar-->
	<nav class ="navbar navbar-dark bg-primary mb-4">
        <div class ="container">
            <a class ="navbar-brand" href ="#">Polls</a>
        </div>
    </nav>
	<div class ="container">
		<div class ="row">
			<div class =".col-md-6 m-auto">
				<!--Content of Block which is replaced while extending this file-->
				{% block content %}{% endblock %}
			</div>
		</div>
	</div>
</body>

</html>